"use client";

import { useMemo, useState } from "react";
import { PageHeader, adminCx } from "@/components/admin/admin-primitives";
import { QueueCard, StatusPill } from "@/components/admin/growth-ui";
import { Calendar, Filter, PenSquare } from "lucide-react";
import { useGrowthState } from "@/components/admin/use-growth-state";

type FilterStatus = "all" | "draft" | "ready" | "scheduled" | "needs-review";

const FILTERS: FilterStatus[] = ["all", "draft", "ready", "scheduled", "needs-review"];

function statusTone(status: string): "neutral" | "good" | "warn" | "muted" {
  if (status === "scheduled" || status === "posted") return "good";
  if (status === "needs-review" || status === "failed") return "warn";
  if (status === "draft") return "muted";
  return "neutral";
}

export default function AdminContentQueuePage() {
  const { state } = useGrowthState();
  const [status, setStatus] = useState<FilterStatus>("all");
  const [query, setQuery] = useState("");

  const filtered = useMemo(() => {
    return state.contentQueue.filter((item) => {
      if (status !== "all" && item.status !== status) return false;
      if (query && !item.title.toLowerCase().includes(query.toLowerCase())) return false;
      return true;
    });
  }, [state.contentQueue, status, query]);

  return (
    <div>
      <PageHeader
        index={20}
        title="Content Queue"
        description="Manage text-only social posts generated by your AI workflows. Keep media-heavy posts in draft until visual assets are ready."
      />

      <div className="max-w-3xl">
        <div className="flex flex-wrap items-center gap-2 mb-5">
          <div className="relative flex-1 min-w-[220px]">
            <PenSquare size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/20" />
            <input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search queued post..."
              className={`${adminCx.input} pl-9`}
            />
          </div>

          <div className="flex items-center gap-1 border border-white/[0.06] p-1">
            <Filter size={12} className="text-white/20 ml-2 mr-1" />
            {FILTERS.map((filter) => (
              <button
                key={filter}
                onClick={() => setStatus(filter)}
                className={`px-2.5 py-1.5 text-[10px] font-['Instrument_Sans'] uppercase tracking-[0.13em] transition-colors ${
                  status === filter ? "bg-white/[0.08] text-white" : "text-white/25 hover:text-white/50"
                }`}
              >
                {filter.replace("-", " ")}
              </button>
            ))}
          </div>
        </div>

        <div className="space-y-2">
          {filtered.map((item) => (
            <QueueCard
              key={item.id}
              title={item.title}
              meta={`${item.channel.toUpperCase()} • ${item.tone} • ${item.scheduledFor}`}
              status={item.status}
              tone={statusTone(item.status)}
            />
          ))}
        </div>

        {filtered.length === 0 && (
          <div className="border border-white/[0.06] p-8 text-center mt-2">
            <p className="text-[11px] text-white/25 font-['Instrument_Sans'] tracking-[0.14em] uppercase">
              No posts match current filters
            </p>
          </div>
        )}

        <div className="mt-8 p-4 border border-white/[0.05] bg-white/[0.02]">
          <div className="flex items-start gap-2">
            <Calendar size={14} className="text-[#E2B93B]/65 mt-0.5" />
            <div>
              <p className="text-[10px] text-white/35 font-['Instrument_Sans'] tracking-[0.14em] uppercase">
                Posting policy
              </p>
              <p className="text-[10px] text-white/40 font-['Instrument_Sans'] mt-1 leading-relaxed">
                Auto-publish only items in <StatusPill label="scheduled" tone="good" /> state and skip any
                record marked <StatusPill label="needs-review" tone="warn" />.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
